apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mern-auth-staging

resources:
  - ../../base

images:
  - name: mern-auth
    newName: 203848753188.dkr.ecr.ap-southeast-1.amazonaws.com/mern-auth/stage
    newTag: latest
